/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.sdksamples;

import com.impinj.octane.AntennaConfigGroup;
import com.impinj.octane.ImpinjReader;
import com.impinj.octane.OctaneSdkException;
import com.impinj.octane.ReportConfig;
import com.impinj.octane.ReportMode;
import com.impinj.octane.SearchMode;
import com.impinj.octane.Settings;




/**
 *
 * @author matee
 */
public class A_RFID_SPEED extends javax.swing.JFrame {
    private static short antennaId1 = 1;
    private static short antennaId2 = 9;
    private static short[] antennaIds = new short[2];
    /**
     * Creates new form NewJFrame
     */
    public A_RFID_SPEED() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Speed = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ANT1 = new javax.swing.JTextField();
        ANT2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Speed.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Speed.setText("Speed");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ANT1.setText("1");
        ANT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANT1ActionPerformed(evt);
            }
        });

        ANT2.setText("9");
        ANT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANT2ActionPerformed(evt);
            }
        });

        jLabel1.setText("First Anthena");

        jLabel2.setText("Second Anthena");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("km/h");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ANT1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ANT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35))))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Speed, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Speed, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Speed.setText("Smrdiis zmrde");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ANT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANT1ActionPerformed

    private void ANT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANT2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
                    // Vytvoření instance GUI A_RFID_SPEED
        A_RFID_SPEED frame = new A_RFID_SPEED();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
            }
        });
       
        
        try {
            // Nastavení IP adresy nebo hostname čtečky
            String hostname = "speedwayr-12-6a-dc.local";
            ImpinjReader reader = new ImpinjReader();

            // Připojení k čtečce
            System.out.println("Connecting");
            reader.connect(hostname);

            // Získání výchozích nastavení
            Settings settings = reader.queryDefaultSettings();

            // Konfigurace reportu
            ReportConfig report = settings.getReport();
            report.setIncludeAntennaPortNumber(true);
            report.setMode(ReportMode.Individual);

            // Nastavení režimu RF a hledání
            settings.setRfMode(1000);
            settings.setSearchMode(SearchMode.DualTarget);
            settings.setSession(1);
                        
            
            antennaIds[0] = antennaId1;
            antennaIds[1] = antennaId2;
            
            // Povolení obou antén a nastavení maximálního výkonu
            AntennaConfigGroup antennas = settings.getAntennas();
            antennas.disableAll(); // Zakázání všech antén
            antennas.enableById(antennaIds);
            
             for (short i = 1; i <= antennaIds.length; i++) {
                antennas.getAntenna(i).setIsMaxRxSensitivity(true);
                antennas.getAntenna(i).setIsMaxTxPower(true);
            }


            // Použití nově upravených nastavení
            System.out.println("Applying Settings");
            reader.applySettings(settings);
            // Přiřazení obsluhy události pro reportování tagů

             Speed_meter_1 speed = new Speed_meter_1(frame,17,antennaId2,antennaId1); // Předání instance frame do Speed_meter
            reader.setTagReportListener(speed);
            
            // Zahájení čtení
            System.out.println("Starting");
            reader.start();

            // Čekání na stisknutí klávesy Enter
            System.out.println("Press Enter to exit.");
            new java.util.Scanner(System.in).nextLine();

            // Zastavení čtení
            System.out.println("Stopping");
            reader.stop();

            // Odpojení od čtečky
            System.out.println("Disconnecting");
            reader.disconnect();
        } catch (OctaneSdkException ex) {
            System.out.println("Octane SDK exception: " + ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
            ex.printStackTrace(System.out);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ANT1;
    private javax.swing.JTextField ANT2;
    public javax.swing.JLabel Speed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
